name: TryHackMe Update Badge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    # Node.js uyarısını kaldırma
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Klasör Oluştur
        run: mkdir -p assets
        
      - name: Rozeti İndir
        run: curl -L -o assets/thm_propic.svg "https://tryhackme-badges.vercel.app/api/user/badge/RennnSkywalker"
        
      - name: GitHub'a Kaydet ve Pushla
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Güncel TryHackMe rozeti eklendi 🚀"
          file_pattern: 'assets/thm_propic.svg'
